config/routes.rb
Diplomacy::Application.routes.draw do
  resources :games do
    member do
      get 'join'
    end
  end

  # Authentication Routes
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root to: 'games#new'
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :players
  has_many :users, through: :players
  belongs_to :creator, foreign_key: :user_id, class_name: 'User'

  validates :creator, presence: true

  SUPER_POWERS = [
      'Austria',
      'England',
      'France',
      'Germany',
      'Italy',
      'Russia',
      'Turkey'
  ].freeze

  def add_player(user)
    already_assigned = players.collect { |p| p.super_power }
    assignment = (SUPER_POWERS - already_assigned).sample
    Player.create(game: self, user: user, super_power: assignment)
  end

  def player_from_user(user)
    players.where(user_id: user.id).first
  end

end

app/models/move.rb
class Move < ActiveRecord::Base
  validates :request, :turn, presence: true
  belongs_to :player
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :game
  belongs_to :user

  validates :super_power, inclusion: {in: Game::SUPER_POWERS}
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["nickname"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @game = Game.new
  end

  def create
    @game = Game.create(creator: current_user)
    redirect_to @game
  end

  def show
    @game = Game.find(params.require(:id))
    @player = @game.player_from_user(current_user)
  end

  def join
    @game = Game.find(params.require(:id))
    player = @game.add_player(current_user)
    flash[:success] = "You have joined the game as #{player.super_power}."
    redirect_to game_path(@game)
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  def new
    @move = Move.new
    @title = 'Submit a move'
  end

  def create
    Move.create(move_params)
    redirect_to :new
  end

  private

  def move_params
    params.require(:move).permit(:super_power, :turn, :request)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: [:create]
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in!"
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/new.html.erb
<%= form_for @game do |f| %>
  <%= f.submit 'Start a new game', class: 'btn btn-primary' %>
<% end %>

app/views/games/show.html.erb
<p>Use this URL to invite players to join</p>
<p><%= join_game_url(@game) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<title>Diplomacy</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <header>
    <% if current_user %>
      Signed in as <%= current_user.name %>!
    <%= link_to "Sign out", signout_path %>
  <% else %>
      <%= link_to "Sign in with Twitter", "/auth/twitter" %>
  <% end %>
  </header>
  <h1>Diplomacy <%= content_tag :small, @title if @title %></h1>
  <%= render 'shared/flash' unless flash.empty? %>
  <%= yield %>
</div>

</body>
</html>

app/views/moves/new.html.erb
<%= form_for @move, html: { role: 'form' } do |f| %>
  <div class="form-group">
    <%= f.label :request %>
    <%= f.text_field :request, class: 'form-control', placeholder: 'ex: A POR -> SPA' %>
  </div>

  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/shared/_flash.html.erb
<div id="flash_messages">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, :class => "alert alert-#{key}") %>
  <% end %>
</div>